### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by LotsofPixels** [postcode-nl/PostcodeNl_Api_Magento2#57]
Hi, Getting a error at bin/magento setup:upgrade

Please remove the , at line 34 in endor/postcode-nl/api-magento2-module/Setup/Patch/Data/UpdateApiStatusConfig.php on line 34

 public function __construct(
        ApiClientHelper $apiClientHelper,
        WriterInterface $configWriter,
        StoreConfigHelper $storeConfigHelper,
        ConfigInterface $resourceConfig,
    ) {

**Comment by JerrySmidt** [comment]
Ah, how did that comma get in there. Thanks for reporting.

Fixed in release 3.1.7.1.

**Comment by gunneman** [comment]
Unfortunately this is still not working. Running composer update won't update the extension from 3.1.7 to 3.1.7.1. I suspect this has something to do with the version change from 3 to 4 digits.

**Comment by arko-betersport** [comment]
I have the same problem, it looks like packagist hasn't been updated [https://packagist.org/packages/postcode-nl/api-magento2-module](https://packagist.org/packages/postcode-nl/api-magento2-module)

**Comment by barryvdh** [comment]
This re-appeared in the latest version, I've added PR to fix some instances: https://github.com/postcode-nl/PostcodeNl_Api_Magento2/pull/86
